### ISSUE TITLE
Cannot install extension to collections

### ISSUE THREAD

**Issue by dovisto** [NielZeeman/team-capacity-extension#7] opened 2018-02-08 14:23 UTC
On-premise TFS 2017 Update 3. I can upload the extension to gallery, but installation option is not shown or greyed out.

**Comment by NielZeeman** [comment] 2018-02-21 06:19
Hi,
I have noticed that the install option appears greyed out, but you can still click on it.
It it still does not work, please log an issue with the vsts market place team, as extension writers have no control over this.

**Comment by NielZeeman** [comment] 2019-02-18 13:34
Duplicate of #14

**Comment by NielZeeman** [comment] 2019-02-18 13:35
Please see resolution on #14

**Closed by NielZeeman** 2019-02-18 13:35 UTC
